In [ ]:
#1D Array   
import numpy as np  #importing NumPy library and using it as np instead of numpy
arr_1d = np.array([10,20,30,40,50])
print(arr_1d)
print(arr_1d.ndim)


#2D Array
import numpy as np
arr_2d = np.array([[10,20,30,40],[30,40,50,60]])
print(arr_2d)
print(arr_2d.ndim)


#3D Array
import numpy as np
arr_3d = np.array([[[10,20,30],[20,30,40],[30,40,50]]])
print(arr_3d)
print(arr_3d.ndim)

In [ ]:
#creating arrrays with default values

#taking '0' as the default value
import numpy as np
arr1 = np.zeros(1)  #np.zeros(shape of array) == syntax
arr2 = np.zeros(2)
arr3 = np.zeros(3)
print(arr1)
print(arr2)
print(arr3)


#taking '1' as the default value
import numpy as np
yt = np.ones((3,2))   #np.ones(shape) == syntax
print(yt)


#taking a certain value as the default value
import numpy as np
utk = np.full((3,4),7)
print(utk)


[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [22]:
#creating sequences of numbers in numpy

#1. using 'arange'
import numpy as np
yuvti = np.arange(0,10,2)   #arange(start,stop,step) == syntax(just like 'range' function in python
print(yuvti)

[0 2 4 6 8]


In [ ]:
#creating identity matrix

import numpy as np
gawk = np.eye(3)
print(gawk)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
