In [6]:
# NumPy Array Properties

# using .shape
import numpy as np
riya = np.array([[1,2,3],[4,5,6]])
print(riya.shape)


#using .size
import numpy as np
riya = np.array([[1,2,3],[4,5,6],["riya","mohit","deepak"]])
print(riya.dtype)

#using .ndim
import numpy as np
riya = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(riya.ndim)

(2, 3)
<U21
3


In [8]:
#changing the datatype of the array
import numpy as np

queen = np.array([[1.2,2.3,3.4],[4.5,5.6,6.7]])
print(queen)
print(queen.dtype)

new_queen = queen.astype(int)
print(new_queen)
print(new_queen.dtype)

[[1.2 2.3 3.4]
 [4.5 5.6 6.7]]
float64
[[1 2 3]
 [4 5 6]]
int64


In [14]:
#Mathematical Operations on array
import numpy as np

maths = np.array([10,20,30])
print(maths+2)
print(maths//2)
print(maths**2)
print(maths%2)

[12 22 32]
[ 5 10 15]
[100 400 900]
[0 0 0]


In [6]:
#Aggregation Functions(SUM,AVERAGE,MINIMUM,MAXIMUM)

import numpy as np
#1.Sum Function
vansh = np.array([[10,20,30],[40,50,60]])
print(np.sum(vansh))

#2.Average Function
vansh = np.array([[10,20,30],[40,50,60]])
print(np.average(vansh)) #or print(np.mean(vansh))

#3.Minimum Function
vansh = np.array([[10,20,30],[40,50,60]])
print(np.min(vansh))

#4.Maximum Function
vansh = np.array([[10,20,30],[40,50,60]])
print(np.max(vansh))

#5.Standard Deviation Function
vansh = np.array([[10,20,30],[40,50,60]])
print(np.std(vansh))

#6.Variance Function
vansh = np.array([[10,20,30],[40,50,60]])
print(np.var(vansh))

210
35.0
10
60
17.07825127659933
291.6666666666667
