In [ ]:
#Indexing
import numpy as np

#1D array
tiger = np.array([10,20,30])
print(tiger[0])
print(tiger[-1])

#2D array
tiger = np.array(
                    [
                        [
                            [10,20,30],["a","b","c"],
                            [40,50,60],
                            [70,80,90]
                        ],
                        [
                            ["d","e","f"],
                            [100,200,300]
                        ],
                        [
                            ["rocky","mohit","jimmy"],
                            [900,800,700]
                        ]
                    ]
                )
print(tiger[2,0])

10
30
[10 20 30]


In [ ]:
#slicing

import numpy as np
joker = np.array([10,20,30,40,50,60,70,80])

print(joker[0:7:2])
print(joker[-1:-8:-2])
print(joker[::-2]) #this meams that we have only mentioned the "step"
print(joker[:4])   #this means that we have only mentioned the elements from '0' to '3'
print(joker[-1:])  #to reverse the sequence/array 

[10 30 50 70]
[80 60 40 20]
[80 60 40 20]
[10 20 30 40]
[10 20 30 40 50 60 70]


In [ ]:
#fancy indexing - used to select selective elements at once

import numpy as np
fancy = np.array([10,20,30,40,50])

print(fancy[[0,2,4]])  #we need to pass the list of indices and not like this --> [0,2,4] always [[0,2,4]]

[10 30 50]


In [33]:
#boolean masking

import numpy as np
mask = np.array([10,20,30,40,50,60,70,80,90])

print(mask[mask>45])
print(mask[mask%20==0])

[50 60 70 80 90]
[20 40 60 80]
