In [5]:
#reshaping
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8])

reshaped_arr = arr.reshape(2,4)
print(reshaped_arr)

[[1 2 3 4]
 [5 6 7 8]]


--> Reshaping does not create a copy of the array it just changes the dimension of the arrays by reshaping it.

In [ ]:
#ravel() --> used to return the view of the array without making a copy of it. Modifications are allowed in the main array.
#flatten() --> does not return the view of the array and makes a copy of it. No modifications are allowed in the main array.

#these are both are basically used for converting multi-D array into 1-D array

import numpy as np

arr_2d = np.array([[1,2,3], [4,5,6,]])
print(arr_2d.ravel())
print(arr_2d.flatten())

#the output of both the functions is same while viewing but the difference is of modifications and copy attribute of these functions

[1 2 3 4 5 6]
[1 2 3 4 5 6]
