In [ ]:
# np.insert(arr, index, value, axis)--> used for inserting an element at a specific position

#for 1D array
import numpy as np
arr = np.array([1,2,3,4,5,6])
new_arr = np.insert(arr, 4, 100)
print(new_arr)

#for 2D array
arr_2d = np.array([[1,2], [3,4]])

new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=0)
print(new_arr_2d)

new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=1)
print(new_arr_2d)

new_arr_2d = np.insert(arr_2d, 1, [5,6], axis=None)
print(new_arr_2d)

[  1   2   3   4 100   5   6]
[[1 2]
 [5 6]
 [3 4]]
[[1 5 2]
 [3 6 4]]
[1 5 6 2 3 4]


The syntax of insert function is np.insert(array, index, value, axis)

array = the array which needs to be modified, index = the index at which the element is to be placed, value = the value which is to be placed, axis = decides where the values will be inserted in a multidimensional array --> {axis=0(means along the row) & axis=1(means along the columns)}

In [ ]:
# np.delete(arr, index, axis) --> delete an element from a specified position
import numpy as np

#1D
arr = np.array([1,2,3])
new_arr = np.delete(arr, 1)
print(new_arr)

#2D
arr = np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])

new_arr = np.delete(arr, 2, axis=0)
print(f"new_arr_along_row = {new_arr}")

new_arr = np.delete(arr, 2, axis=1)
print(f"new_arr_along_column = {new_arr}")

[1 3]
new_arr_along_row = [[1 2 3]
 [3 4 5]
 [7 8 9]]
new_arr_along_column = [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [37]:
# np.append() --> to add the element at the last of an array
import numpy as np

#for 1D
arr = np.array([[1,2,3,4],[10,20,30,40]])

new_arr = np.append(arr, [[50,60,70,80],[5,6,7,8]])
print(f"new_arr1 = {new_arr}")
new_arr = np.append(arr, [[50,60,70,80],[5,6,7,8]], axis=0)
print(f"new_arr2 = {new_arr}")
new_arr = np.append(arr, [[50,60,70,80],[5,6,7,8]], axis=1)
print(f"new_arr3 = {new_arr}")

new_arr1 = [ 1  2  3  4 10 20 30 40 50 60 70 80  5  6  7  8]
new_arr2 = [[ 1  2  3  4]
 [10 20 30 40]
 [50 60 70 80]
 [ 5  6  7  8]]
new_arr3 = [[ 1  2  3  4 50 60 70 80]
 [10 20 30 40  5  6  7  8]]


In [39]:
# np.concatenate(array1, array2, array3,..., arrayn) --> used to join two or more arrays
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])

joint_arr = np.concatenate((arr1, arr2, arr3))
print(f"initial_arr1 = {joint_arr}")

arr1 = np.array([[1,2,3],[10,20,30]])
arr2 = np.array([[4,5,6],[40,50,60]])
arr3 = np.array([[7,8,9],[70,80,90]])

joint_arr = np.concatenate((arr1, arr2, arr3), axis=None)
print(f"joint_arr1 = {joint_arr}")

joint_arr = np.concatenate((arr1, arr2, arr3), axis=0)
print(f"joint_arr2 = {joint_arr}")

joint_arr = np.concatenate((arr1, arr2, arr3), axis=1)
print(f"joint_arr3 = {joint_arr}")

initial_arr1 = [1 2 3 4 5 6 7 8 9]
joint_arr1 = [ 1  2  3 10 20 30  4  5  6 40 50 60  7  8  9 70 80 90]
joint_arr2 = [[ 1  2  3]
 [10 20 30]
 [ 4  5  6]
 [40 50 60]
 [ 7  8  9]
 [70 80 90]]
joint_arr3 = [[ 1  2  3  4  5  6  7  8  9]
 [10 20 30 40 50 60 70 80 90]]


In [50]:
# np.vstack((arr1,arr2,arr3,...,arrn)) --> for vertically stacking the arrays
# np.hstack((arr1,arr2,arr3,...,arrn)) --> for horizontically stacking the arrays

import numpy as np

arr_1 = np.array([1,2,3])
arr_2 = np.array([3,4,5])

print(f"Horizontical Stack = {np.hstack((arr_1,arr_2))}")
print(f"Vertical Stack = {np.vstack((arr_1,arr_2))}")

Horizontical Stack = [1 2 3 3 4 5]
Vertical Stack = [[1 2 3]
 [3 4 5]]


In [58]:
# splitting the array
import numpy as np

# np.split() for equally splitting
arr = np.array([1,2,3,4,5,6])
print(f"Equal Split = {np.split(arr, 2)}")

# np.vsplit() for verticallylly splitting
arr = np.array([[1,2,3],[7,8,9]])
print(f"V-Split = {np.vsplit(arr, 1)}")

# np.hsplit() for horizontally splitting
arr = np.array([1,2,3,4,5,6])
print(f"H-Split = {np.split(arr, 2)}")

Equal Split = [array([1, 2, 3]), array([4, 5, 6])]
V-Split = [array([[1, 2, 3],
       [7, 8, 9]])]
H-Split = [array([1, 2, 3]), array([4, 5, 6])]
