||Vectorization|| --> Performing operations on entire arrays at once without using explicit Python loops. ||Broadcasting|| --> NumPy’s ability to automatically match array shapes during operations.

                                                          || B R O A D C A S T I N G ||                                                                 

In [ ]:
#here we use loops for applying any operation over a dataset plus the dataset here is very small as compared to real life dataset

prices = [100,200,300]
discount = 10

final_prices = []

for i in prices:
    discounted = i - (i*(discount/100))
    final_prices.append(discounted)
print(final_prices)

#to solve this problem we use broadcasting in numpy which helps in applying operation on a larger dataset wihtout using the loop, which is more faster and easier.

[90.0, 180.0, 270.0]


In [ ]:
# now how can we solve this problem --> Broadcasting

import numpy as np
prices = np.array([100,200,300])
discount = 10
final_prices = prices - (prices*(10/100))
print(final_prices)

# faster, easier, and consumes lesser memory

[ 90. 180. 270.]


We can perform all the operations on arrays when two or more arrays are of same shape or one is an array an another is a vector

In [11]:
matrix1 = np.array([[100,200,300],[400,500,600]])
vector1 = np.array([1,2,3])

result1 = matrix1 + vector1
print(result1)

matrix2 = np.array([[100,200,300],[400,500,600]])
vector2 = np.array([2])

result2 = vector2*matrix2
print(result2)
# but if the two arrays are of diiferent types, then it will throw error

[[101 202 303]
 [401 502 603]]
[[ 200  400  600]
 [ 800 1000 1200]]


But if the two arrays are of different shapes, then it will throw error like below example

In [ ]:
arr1 = np.array([[10,20,30],[40,50,60]])  #shape = (2,3)
arr2 = np.array([1,2])  #shape = (2,)
result3 = arr1 + arr2
print(result3)

# so what is the solution of this? --> '(array_name).reshape' function

                                                          || V E C T O R I S A T I O N ||                                                               

In [ ]:
# performing operations in python
list1 = [1,2,3]
list2 = [4,5,6]

result = [x+y for x,y in zip(list1,list2)]
print(result)

[5, 7, 9]


In [ ]:
#performing operations in NumPy
list1 = np.array([1,2,3])
list2 = np.array([4,5,6])

result = list1 + list2
print(result)

# faster, easier and consumes lesser memory

[5 7 9]
